dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ez78112.ca-central-1.aws

      # User/password auth
      user: jcamiloparra
      password: 3142645279aMA

      role: dbt_dev_role
      database: demo_dbt
      warehouse: dbt_dev_wh
      schema: public
      threads: 200
      client_session_keep_alive: False
      query_tag: dbt

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false